package ee.kaarel.familybudgetapplication.model;

public enum NotificationType {
    MONEY_RECEIVED,
    SHARED_ACCOUNT_TRANSACTION,
    ACCOUNT_DELETION_APPROVAL_REQUIRED,
    ACCOUNT_SHARED,
    ACCOUNT_UNSHARED,
    RECURRING_PAYMENT_UNPAID,
    RECURRING_PAYMENT_DUE
}
