create table family_savings_selections (
    id bigint generated by default as identity primary key,
    family_id bigint not null unique,
    selected_account_ids varchar(2000) not null default ''
);
